networks:
  hospital-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: main-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: db_pass
    secrets:
      - db_pass
    volumes:
      - mongo-volume:/data/db
    networks:
      - hospital-network

  backend:
    build: .
    container_name: node-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env 
    depends_on:
      - mongodb
    networks:
      - hospital-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/api.neyromed.uz/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/api.neyromed.uz/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - backend
    networks:
      - hospital-network

secrets:
  db_pass:
    file: parol.txt

volumes:
  mongo-volume:
